title: Minimal theme
logo: https://avatars.githubusercontent.com/u/60959482?s=400&u=2024d190f7de740086b56ecc195c6eb9976af9ac&v=4
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
